# ####################################################
# ASP.NET Async Communication
#   * Source code: github.com/hd9/aspnet-async-communication
#   * More about this app at: blog.hildenco.com
# ####################################################

# If you're looking to run all the services, run:
# docker-compose up

version: '3.7'

services:

  rabbitmq:
    image: rabbitmq:management-alpine
    environment:
      - todo
    expose:
      - "5672"
    ports:
      - "5672:5672"
      - "8012:15672"
